name: Build and Test
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  build-and-test:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run check

      - name: Lint code
        run: npm run lint

      - name: Build app
        run: npm run build
